// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxqWPOZLqXI8gAVGx0N_cY9ZjWIuW2WQw',
    appId: '1:360610786266:web:0943a25be4ceb3a4f06ee3',
    messagingSenderId: '360610786266',
    projectId: 'elysium-pk',
    authDomain: 'elysium-pk.firebaseapp.com',
    storageBucket: 'elysium-pk.appspot.com',
    measurementId: 'G-NDNN4K242C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgn7SMKtWo4rNJpVLhYP62Ed5lREeuz_s',
    appId: '1:360610786266:android:5c563afb6f549fb3f06ee3',
    messagingSenderId: '360610786266',
    projectId: 'elysium-pk',
    storageBucket: 'elysium-pk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAjhuNzVicLMWE0-nPEZiPxp1EtTA5p_Y',
    appId: '1:360610786266:ios:d15b49800f0f75d9f06ee3',
    messagingSenderId: '360610786266',
    projectId: 'elysium-pk',
    storageBucket: 'elysium-pk.appspot.com',
    androidClientId: '360610786266-2n6rskn96q3te3397lhrnlvgoqs2j6lk.apps.googleusercontent.com',
    iosClientId: '360610786266-qqlrbehhcftaco9ra0dtt2e200knm7q2.apps.googleusercontent.com',
    iosBundleId: 'com.example.elysium',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAjhuNzVicLMWE0-nPEZiPxp1EtTA5p_Y',
    appId: '1:360610786266:ios:d15b49800f0f75d9f06ee3',
    messagingSenderId: '360610786266',
    projectId: 'elysium-pk',
    storageBucket: 'elysium-pk.appspot.com',
    androidClientId: '360610786266-2n6rskn96q3te3397lhrnlvgoqs2j6lk.apps.googleusercontent.com',
    iosClientId: '360610786266-qqlrbehhcftaco9ra0dtt2e200knm7q2.apps.googleusercontent.com',
    iosBundleId: 'com.example.elysium',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxqWPOZLqXI8gAVGx0N_cY9ZjWIuW2WQw',
    appId: '1:360610786266:web:712aff46979a7c12f06ee3',
    messagingSenderId: '360610786266',
    projectId: 'elysium-pk',
    authDomain: 'elysium-pk.firebaseapp.com',
    storageBucket: 'elysium-pk.appspot.com',
    measurementId: 'G-MCPJ8CCQ3F',
  );

}